version: "3"
# 管理的服务
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.33
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/logs:/logs
      - ./data/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: always

  redis:
    # 指定镜像
    image: redis
    container_name: redis
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - ./data/redis/redis.conf:/etc/redis/redis.conf
    command:
      # 执行的命令
      redis-server /etc/redis/redis.conf --requirepass WudiHX0Q3A98eVqy
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.1.2
    restart: always
    container_name: xxl-job-admin
    environment:
      TZ: Asia/Shanghai
      PARAMS: '--spring.datasource.url=jdbc:mysql://10.1.2.68:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root  --spring.datasource.password=123456'
    ports:
      - 8085:8080
    volumes:
      - ./data/xxl_job/applogs:/data/xxl_job/applogs
  zookeeper:
    image: zookeeper:3.4.11
    container_name: zookeeper
    ports:
      - 2181:2181
  activemq:
    #定义主机名
    hostname: activemq
    container_name: activemq
    #使用的镜像
    image: webcenter/activemq
    #容器的映射端口
    ports:
      - 61616:61616
      - 8161:8161
    restart: always
    #定义挂载点
    volumes:
      - ./data/activemq:/data/activemq
      - ./data/activemq:/var/log/activemq

