###################  server  ###################
server:
  port: 8080
  tomcat:
    max-connections: 20000
    max-threads: 5000
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
logging:
  config: classpath:log4j2.xml


