###################  server  ###################
server:
  port: 5000
spring:
  datasource:
    webrtcdb:
      url: jdbc:mysql://localhost:3306/webrtcdb?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
